// 全球汽车科普数据集
// 字段说明：
//   id           唯一标识
//   name         车型名称
//   brand        品牌
//   country      产地/国家
//   category     类型（超级跑车 / 跑车 / 豪华轿车 / SUV / 电动车 / 越野 / 经典老爷车 / 家用轿车）
//   year         代表年份 / 车型年代
//   priceRMB     参考价格区间（人民币，近似）
//   engine       动力形式
//   power        最大功率
//   topSpeed     最高车速（km/h）
//   accel        0-100 km/h 加速（秒）
//   drivetrain   驱动形式
//   seats        座位数
//   accent       主题渐变色（用于卡片配色）
//   emoji        代表图标
//   summary      一句话简介
//   description  科普正文
//   facts        冷知识 / 有趣事实（数组）

const CARS = [
  {
    id: "bugatti-chiron",
    name: "Chiron 凯龙",
    brand: "Bugatti 布加迪",
    country: "法国",
    category: "超级跑车",
    year: 2016,
    priceRMB: "约 3000 万元",
    engine: "8.0L W16 四涡轮增压",
    power: "1500 马力",
    topSpeed: 420,
    accel: 2.4,
    drivetrain: "四驱",
    seats: 2,
    accent: "linear-gradient(135deg,#0f2027,#2c5364)",
    emoji: "🏎️",
    summary: "地表最快量产车之一，W16 四涡轮的工程巅峰。",
    description:
      "布加迪 Chiron 搭载独一无二的 8.0 升 W16 发动机，由四个涡轮增压器供气，输出高达 1500 马力。它是对速度、工艺与极致工程的致敬，散热系统每分钟可处理约 6 万升空气。",
    facts: [
      "W16 发动机相当于把两台 V8 拼在一起。",
      "以最高速行驶时，一箱油仅够跑约 9 分钟。",
      "Chiron 之名来自赛车手 Louis Chiron。",
    ],
  },
  {
    id: "ferrari-f8",
    name: "F8 Tributo",
    brand: "Ferrari 法拉利",
    country: "意大利",
    category: "超级跑车",
    year: 2019,
    priceRMB: "约 300 万元",
    engine: "3.9L V8 双涡轮增压",
    power: "720 马力",
    topSpeed: 340,
    accel: 2.9,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#8e0e00,#1f1c18)",
    emoji: "🐎",
    summary: "法拉利跃马精神的中置引擎代表作。",
    description:
      "F8 Tributo 是法拉利对其屡获殊荣的 V8 发动机的致敬之作。中置后驱布局带来极佳的操控平衡，空气动力学套件在保证下压力的同时兼顾了优雅线条。",
    facts: [
      "其 V8 发动机曾多次获得‘国际年度发动机’大奖。",
      "跃马标志源自一战飞行员的战机徽记。",
    ],
  },
  {
    id: "lamborghini-aventador",
    name: "Aventador",
    brand: "Lamborghini 兰博基尼",
    country: "意大利",
    category: "超级跑车",
    year: 2011,
    priceRMB: "约 400 万元",
    engine: "6.5L V12 自然吸气",
    power: "770 马力",
    topSpeed: 350,
    accel: 2.9,
    drivetrain: "四驱",
    seats: 2,
    accent: "linear-gradient(135deg,#f7971e,#3a1c00)",
    emoji: "🐂",
    summary: "剪刀门与自吸 V12 的狂野图腾。",
    description:
      "Aventador 以标志性的剪刀门和轰鸣的自然吸气 V12 发动机成为超跑图腾。棱角分明的楔形设计灵感来自战斗机与隐形战机。",
    facts: [
      "兰博基尼车型多以著名斗牛命名。",
      "Aventador 是一头曾在斗牛场英勇战斗的公牛之名。",
    ],
  },
  {
    id: "porsche-911",
    name: "911 Carrera",
    brand: "Porsche 保时捷",
    country: "德国",
    category: "跑车",
    year: 1963,
    priceRMB: "约 130 万元起",
    engine: "3.0L 水平对置六缸涡轮增压",
    power: "385 马力",
    topSpeed: 293,
    accel: 4.0,
    drivetrain: "后驱 / 四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#414345,#232526)",
    emoji: "🛞",
    summary: "延续 60 年的后置引擎跑车传奇。",
    description:
      "保时捷 911 是史上最具辨识度的跑车之一，标志性的后置水平对置发动机布局延续超过一甲子。它兼顾了日常实用性与赛道性能，被誉为‘最好开的超跑’。",
    facts: [
      "911 采用罕见的后置后驱布局，重心独特。",
      "初代 911 因商标问题曾短暂命名为 901。",
    ],
  },
  {
    id: "mazda-mx5",
    name: "MX-5 Miata",
    brand: "Mazda 马自达",
    country: "日本",
    category: "跑车",
    year: 1989,
    priceRMB: "约 30 万元",
    engine: "2.0L 直列四缸自然吸气",
    power: "181 马力",
    topSpeed: 219,
    accel: 6.5,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#e53935,#b71c1c)",
    emoji: "🌤️",
    summary: "史上最畅销的双座敞篷跑车。",
    description:
      "MX-5 用轻量化和精准操控证明了‘乐趣与马力无关’。它是吉尼斯世界纪录认证的最畅销双座敞篷跑车，秉承日语‘人马一体’的设计哲学。",
    facts: [
      "累计销量超过 100 万辆。",
      "设计哲学源自英国经典小跑车 Lotus Elan。",
    ],
  },
  {
    id: "nissan-gtr",
    name: "GT-R R35",
    brand: "Nissan 日产",
    country: "日本",
    category: "跑车",
    year: 2007,
    priceRMB: "约 170 万元",
    engine: "3.8L V6 双涡轮增压",
    power: "570 马力",
    topSpeed: 315,
    accel: 2.9,
    drivetrain: "四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#0575e6,#021b79)",
    emoji: "⚔️",
    summary: "绰号‘战神’的性价比性能怪兽。",
    description:
      "日产 GT-R 凭借先进的四驱系统和双涡轮 V6，以远低于欧洲超跑的价格实现媲美的加速表现，被车迷誉为‘平民超跑’与‘东瀛战神’。",
    facts: [
      "每台发动机由专属工匠手工组装并署名。",
      "曾在纽博格林赛道刷新量产车圈速纪录。",
    ],
  },
  {
    id: "toyota-corolla",
    name: "Corolla 卡罗拉",
    brand: "Toyota 丰田",
    country: "日本",
    category: "家用轿车",
    year: 1966,
    priceRMB: "约 12 万元",
    engine: "1.8L 混合动力",
    power: "122 马力",
    topSpeed: 180,
    accel: 10.9,
    drivetrain: "前驱",
    seats: 5,
    accent: "linear-gradient(135deg,#56ab2f,#a8e063)",
    emoji: "🚗",
    summary: "史上销量第一的传奇家用车。",
    description:
      "卡罗拉是全球累计销量最高的车型，以耐用、省油、低故障率著称，是无数家庭的第一辆车，堪称‘可靠’的代名词。",
    facts: [
      "全球累计销量超过 5000 万辆。",
      "名字 Corolla 在拉丁语中意为‘花冠’。",
    ],
  },
  {
    id: "vw-golf",
    name: "Golf 高尔夫",
    brand: "Volkswagen 大众",
    country: "德国",
    category: "家用轿车",
    year: 1974,
    priceRMB: "约 14 万元",
    engine: "1.4L 涡轮增压",
    power: "150 马力",
    topSpeed: 216,
    accel: 8.5,
    drivetrain: "前驱",
    seats: 5,
    accent: "linear-gradient(135deg,#334d50,#cbcaa5)",
    emoji: "⛳",
    summary: "定义了‘两厢车’级别的标杆。",
    description:
      "大众高尔夫开创并定义了紧凑型两厢车市场，其 GTI 版本更缔造了‘钢炮’（Hot Hatch）文化，兼具实用与驾驶乐趣。",
    facts: [
      "Golf 的名字并非高尔夫球，而是德语中的‘湾流’（Gulf Stream）。",
      "GTI 是‘热血小钢炮’的鼻祖之一。",
    ],
  },
  {
    id: "mercedes-sclass",
    name: "S-Class S级",
    brand: "Mercedes-Benz 奔驰",
    country: "德国",
    category: "豪华轿车",
    year: 1972,
    priceRMB: "约 95 万元起",
    engine: "3.0L 直六 + 48V 轻混",
    power: "435 马力",
    topSpeed: 250,
    accel: 4.9,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#232526,#5b6467)",
    emoji: "🎩",
    summary: "汽车科技的‘旗舰试验田’。",
    description:
      "奔驰 S 级长期作为汽车工业的技术风向标，许多如今普及的安全与舒适配置（安全气囊、ABS、ESP）都最早在 S 级上量产应用。",
    facts: [
      "很多主动安全技术都是在 S 级上首发。",
      "三叉星标志代表‘海、陆、空’皆能称霸。",
    ],
  },
  {
    id: "rolls-royce-phantom",
    name: "Phantom 幻影",
    brand: "Rolls-Royce 劳斯莱斯",
    country: "英国",
    category: "豪华轿车",
    year: 1925,
    priceRMB: "约 1000 万元起",
    engine: "6.75L V12 双涡轮增压",
    power: "571 马力",
    topSpeed: 250,
    accel: 5.4,
    drivetrain: "后驱",
    seats: 5,
    accent: "linear-gradient(135deg,#141e30,#243b55)",
    emoji: "👑",
    summary: "顶级手工奢华与静谧的代名词。",
    description:
      "劳斯莱斯幻影是极致奢华的象征，车内静谧到近乎‘无声’。车头的‘欢庆女神’立标与可定制的星空顶棚是其经典标志。",
    facts: [
      "车顶‘星空顶’可由上千根光纤模拟夜空。",
      "‘欢庆女神’立标遇撞击或盗窃会自动缩回车内。",
    ],
  },
  {
    id: "bentley-continental",
    name: "Continental GT",
    brand: "Bentley 宾利",
    country: "英国",
    category: "豪华轿车",
    year: 2003,
    priceRMB: "约 260 万元",
    engine: "6.0L W12 双涡轮增压",
    power: "659 马力",
    topSpeed: 335,
    accel: 3.5,
    drivetrain: "四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#1d4350,#a43931)",
    emoji: "🥂",
    summary: "能优雅巡航也能高速狂奔的豪华GT。",
    description:
      "宾利欧陆 GT 融合了英伦手工内饰与澎湃动力，是‘绅士的高性能座驾’，兼具长途舒适与惊人性能。",
    facts: [
      "内饰真皮与实木均为手工打造，耗时上百小时。",
      "宾利曾在勒芒 24 小时耐力赛多次夺冠。",
    ],
  },
  {
    id: "tesla-model-s",
    name: "Model S Plaid",
    brand: "Tesla 特斯拉",
    country: "美国",
    category: "电动车",
    year: 2012,
    priceRMB: "约 90 万元",
    engine: "三电机纯电动",
    power: "1020 马力",
    topSpeed: 322,
    accel: 2.1,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#c31432,#240b36)",
    emoji: "⚡",
    summary: "重新定义电动车性能的标杆。",
    description:
      "特斯拉 Model S Plaid 用三电机布局实现了媲美超跑的加速，同时保持了轿车的实用性与超长续航，推动了全球电动化浪潮。",
    facts: [
      "Plaid 之名来自科幻喜剧《太空炮弹》中的‘格子超光速’。",
      "0-100 km/h 加速比大多数燃油超跑还快。",
    ],
  },
  {
    id: "byd-han",
    name: "汉 EV",
    brand: "BYD 比亚迪",
    country: "中国",
    category: "电动车",
    year: 2020,
    priceRMB: "约 22 万元",
    engine: "双电机纯电动",
    power: "517 马力",
    topSpeed: 180,
    accel: 3.9,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#0052d4,#4364f7)",
    emoji: "🐉",
    summary: "搭载刀片电池的中国新能源代表。",
    description:
      "比亚迪汉搭载自研‘刀片电池’，在安全性与空间利用率上实现突破，是中国品牌向高端新能源市场进军的标志性车型。",
    facts: [
      "‘刀片电池’通过了严苛的针刺测试，安全性突出。",
      "比亚迪最初是做电池起家的企业。",
    ],
  },
  {
    id: "porsche-taycan",
    name: "Taycan",
    brand: "Porsche 保时捷",
    country: "德国",
    category: "电动车",
    year: 2019,
    priceRMB: "约 100 万元",
    engine: "双电机纯电动",
    power: "761 马力",
    topSpeed: 260,
    accel: 2.8,
    drivetrain: "四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#2b5876,#4e4376)",
    emoji: "🔌",
    summary: "保时捷首款纯电跑车。",
    description:
      "Taycan 是保时捷首款纯电动车，采用领先的 800V 高压架构，兼顾了极致的驾驶质感与快速充电能力。",
    facts: [
      "800V 架构可实现更快充电、更细电缆。",
      "Taycan 在土耳其语中意为‘活泼的小马驹’。",
    ],
  },
  {
    id: "landrover-defender",
    name: "Defender 卫士",
    brand: "Land Rover 路虎",
    country: "英国",
    category: "越野",
    year: 1983,
    priceRMB: "约 80 万元",
    engine: "3.0L 直六 + 轻混",
    power: "400 马力",
    topSpeed: 208,
    accel: 6.1,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#3e5151,#decba4)",
    emoji: "🏔️",
    summary: "征服荒野的英伦硬派越野。",
    description:
      "路虎卫士是硬派越野的传奇，从非洲草原到极地探险都有它的身影。新一代在保留越野硬实力的同时增添了现代豪华科技。",
    facts: [
      "老款卫士曾是英国女王最爱的座驾之一。",
      "极强的涉水与攀爬能力使其成为探险队标配。",
    ],
  },
  {
    id: "jeep-wrangler",
    name: "Wrangler 牧马人",
    brand: "Jeep",
    country: "美国",
    category: "越野",
    year: 1986,
    priceRMB: "约 45 万元",
    engine: "2.0L 涡轮增压",
    power: "272 马力",
    topSpeed: 180,
    accel: 6.7,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#4b6cb7,#182848)",
    emoji: "🧭",
    summary: "源自二战军车的越野图腾。",
    description:
      "Jeep 牧马人血统源自二战军用吉普，标志性的七孔进气格栅、可拆卸车门与车顶是其自由不羁精神的象征。",
    facts: [
      "经典的‘七孔格栅’是 Jeep 的注册标志。",
      "车门和车顶都可拆卸，享受纯粹敞篷越野。",
    ],
  },
  {
    id: "toyota-landcruiser",
    name: "Land Cruiser 陆地巡洋舰",
    brand: "Toyota 丰田",
    country: "日本",
    category: "越野",
    year: 1951,
    priceRMB: "约 90 万元",
    engine: "3.5L V6 双涡轮增压",
    power: "415 马力",
    topSpeed: 210,
    accel: 6.7,
    drivetrain: "四驱",
    seats: 7,
    accent: "linear-gradient(135deg,#603813,#b29f94)",
    emoji: "🗺️",
    summary: "以可靠著称的‘沙漠之王’。",
    description:
      "丰田陆地巡洋舰以极致的耐用性和可靠性闻名，在中东、非洲和澳洲的严酷环境中被广泛信赖，是穿越无人区的首选。",
    facts: [
      "在许多偏远地区，它被视为‘开不坏’的代名词。",
      "联合国与救援组织常选用它作为任务车辆。",
    ],
  },
  {
    id: "bmw-x5",
    name: "X5",
    brand: "BMW 宝马",
    country: "德国",
    category: "SUV",
    year: 1999,
    priceRMB: "约 65 万元",
    engine: "3.0L 直六涡轮增压",
    power: "340 马力",
    topSpeed: 243,
    accel: 5.4,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#005c97,#363795)",
    emoji: "🏙️",
    summary: "开创豪华运动 SUV 的先河。",
    description:
      "宝马 X5 是最早将轿车般操控带入 SUV 的车型之一，被称为‘运动型多用途车（SAV）’，兼顾空间、豪华与驾驶乐趣。",
    facts: [
      "宝马称其为 SAV（运动型多功能车）以强调操控。",
      "蓝白徽标源自巴伐利亚州旗，也常被解读为旋转的螺旋桨。",
    ],
  },
  {
    id: "range-rover",
    name: "Range Rover 揽胜",
    brand: "Land Rover 路虎",
    country: "英国",
    category: "SUV",
    year: 1970,
    priceRMB: "约 150 万元",
    engine: "4.4L V8 双涡轮增压",
    power: "530 马力",
    topSpeed: 250,
    accel: 4.6,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#232526,#414345)",
    emoji: "🏰",
    summary: "豪华与越野兼备的全能旗舰 SUV。",
    description:
      "揽胜将奢华内饰与强悍越野能力完美结合，是‘公路上的绅士、荒野中的斗士’，深受名流与王室青睐。",
    facts: [
      "揽胜是最早把真正豪华引入越野车的车型。",
      "空气悬挂可大幅升降车身以适应不同路况。",
    ],
  },
  {
    id: "ford-mustang",
    name: "Mustang 野马",
    brand: "Ford 福特",
    country: "美国",
    category: "跑车",
    year: 1964,
    priceRMB: "约 45 万元",
    engine: "5.0L V8 自然吸气",
    power: "466 马力",
    topSpeed: 250,
    accel: 4.3,
    drivetrain: "后驱",
    seats: 4,
    accent: "linear-gradient(135deg,#870000,#190a05)",
    emoji: "🐴",
    summary: "美式肌肉车文化的经典图腾。",
    description:
      "福特野马开创了‘Pony Car’品类，以亲民价格提供大排量 V8 的推背感和肌肉车造型，是美式汽车文化的象征。",
    facts: [
      "上市首年即售出超过 40 万辆，创下纪录。",
      "无数好莱坞电影中的追车戏都少不了它的身影。",
    ],
  },
  {
    id: "chevrolet-corvette",
    name: "Corvette C8",
    brand: "Chevrolet 雪佛兰",
    country: "美国",
    category: "跑车",
    year: 2020,
    priceRMB: "约 80 万元",
    engine: "6.2L V8 自然吸气",
    power: "495 马力",
    topSpeed: 312,
    accel: 2.9,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#f12711,#f5af19)",
    emoji: "🌟",
    summary: "转为中置引擎的美国国民超跑。",
    description:
      "第八代 Corvette 首次采用中置发动机布局，以远低于欧洲超跑的价格提供接近的性能，被誉为‘美国人的法拉利’。",
    facts: [
      "C8 是 Corvette 历史上首款中置引擎版本。",
      "Corvette 之名来自一种轻型快速的护卫舰。",
    ],
  },
  {
    id: "koenigsegg-jesko",
    name: "Jesko",
    brand: "Koenigsegg 柯尼塞格",
    country: "瑞典",
    category: "超级跑车",
    year: 2019,
    priceRMB: "约 2000 万元",
    engine: "5.0L V8 双涡轮增压",
    power: "1600 马力",
    topSpeed: 480,
    accel: 2.5,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#000428,#004e92)",
    emoji: "🚀",
    summary: "冲击 500 km/h 极速的瑞典超跑。",
    description:
      "柯尼塞格 Jesko 拥有极致的空气动力学与创新变速箱技术，其 Absolut 版本以挑战量产车最高时速为目标，是纯粹的工程艺术品。",
    facts: [
      "Jesko 以创始人父亲的名字命名。",
      "使用烈性乙醇燃料时功率可达 1600 马力。",
    ],
  },
  {
    id: "volvo-xc90",
    name: "XC90",
    brand: "Volvo 沃尔沃",
    country: "瑞典",
    category: "SUV",
    year: 2002,
    priceRMB: "约 55 万元",
    engine: "2.0L 涡轮增压 + 轻混",
    power: "250 马力",
    topSpeed: 220,
    accel: 8.0,
    drivetrain: "四驱",
    seats: 7,
    accent: "linear-gradient(135deg,#136a8a,#267871)",
    emoji: "🛡️",
    summary: "以安全著称的北欧豪华 SUV。",
    description:
      "沃尔沃 XC90 是安全科技的集大成者，城市安全系统、侧气帘等诸多主动安全技术使其成为‘最安全家用车’的代表。",
    facts: [
      "三点式安全带正是沃尔沃发明并无偿公开的。",
      "沃尔沃承诺以零伤亡为长期安全目标。",
    ],
  },
  {
    id: "citroen-ds",
    name: "DS 女神",
    brand: "Citroën 雪铁龙",
    country: "法国",
    category: "经典老爷车",
    year: 1955,
    priceRMB: "收藏级",
    engine: "2.3L 直列四缸",
    power: "115 马力",
    topSpeed: 188,
    accel: 10.4,
    drivetrain: "前驱",
    seats: 5,
    accent: "linear-gradient(135deg,#654ea3,#eaafc8)",
    emoji: "🌈",
    summary: "超越时代的空气悬挂先驱。",
    description:
      "雪铁龙 DS 在 1955 年问世时以流线造型和液压自适应悬挂震惊世界，法语‘DS’发音同‘女神’（Déesse），至今仍是设计史经典。",
    facts: [
      "曾在戴高乐总统遇袭时凭借液压悬挂高速脱险。",
      "液压悬挂让车辆即使爆胎也能平稳行驶。",
    ],
  },
  {
    id: "vw-beetle",
    name: "Beetle 甲壳虫",
    brand: "Volkswagen 大众",
    country: "德国",
    category: "经典老爷车",
    year: 1938,
    priceRMB: "收藏级",
    engine: "1.6L 水平对置四缸",
    power: "50 马力",
    topSpeed: 130,
    accel: 18.0,
    drivetrain: "后驱",
    seats: 4,
    accent: "linear-gradient(135deg,#f8b500,#fceabb)",
    emoji: "🐞",
    summary: "史上最具亲和力的国民小车。",
    description:
      "大众甲壳虫以圆润可爱的造型和后置风冷发动机风靡全球，是 20 世纪产量最大的单一车型之一，承载了几代人的记忆。",
    facts: [
      "累计产量超过 2100 万辆。",
      "圆滚滚的造型让它拥有了‘甲壳虫’这个昵称。",
    ],
  },
  {
    id: "mini-cooper",
    name: "Mini Cooper",
    brand: "Mini",
    country: "英国",
    category: "家用轿车",
    year: 1959,
    priceRMB: "约 25 万元",
    engine: "2.0L 涡轮增压",
    power: "231 马力",
    topSpeed: 246,
    accel: 6.1,
    drivetrain: "前驱",
    seats: 4,
    accent: "linear-gradient(135deg,#e52d27,#b31217)",
    emoji: "🎯",
    summary: "小车身、大乐趣的操控标杆。",
    description:
      "Mini 以极致紧凑的横置前驱布局把空间利用做到极致，其灵活的‘卡丁车’操控和复古时尚造型使它成为都市个性座驾。",
    facts: [
      "横置前驱布局是它节省空间的关键设计。",
      "曾三度夺得蒙特卡洛拉力赛冠军。",
    ],
  },
  {
    id: "honda-civic",
    name: "Civic Type R",
    brand: "Honda 本田",
    country: "日本",
    category: "家用轿车",
    year: 1972,
    priceRMB: "约 30 万元",
    engine: "2.0L 涡轮增压",
    power: "329 马力",
    topSpeed: 275,
    accel: 5.4,
    drivetrain: "前驱",
    seats: 5,
    accent: "linear-gradient(135deg,#cb2d3e,#ef473a)",
    emoji: "🔴",
    summary: "前驱性能车的‘红头’信仰。",
    description:
      "本田思域从家用轿车衍生出的 Type R 高性能版，凭借高转发动机与出色底盘调校，多次刷新前驱车纽北圈速纪录，是‘买发动机送车’的代表。",
    facts: [
      "Type R 的红色本田标是高性能的信仰图腾。",
      "本田是全球产量最大的发动机制造商之一。",
    ],
  },
  {
    id: "xiaomi-su7",
    name: "SU7 Max",
    brand: "Xiaomi 小米",
    country: "中国",
    category: "电动车",
    year: 2024,
    priceRMB: "约 30 万元",
    engine: "双电机纯电",
    power: "673 马力",
    topSpeed: 265,
    accel: 2.78,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#ff6a00,#1f1f1f)",
    emoji: "📱",
    summary: "手机厂造的车，加速比大多数超跑还快。",
    description:
      "小米 SU7 是小米的第一款汽车。Max 版用前后双电机输出 673 马力，零百加速只要 2.78 秒。它把手机生态直接搬进座舱，手机、平板、车机可以无缝接续使用。",
    facts: [
      "SU7 里的 S 代表 Speed（速度），U 代表 Ultra（极致）。",
      "它的高性能版曾在德国纽博格林赛道刷新四门量产电动车圈速纪录。",
    ],
  },
  {
    id: "nio-et7",
    name: "ET7",
    brand: "NIO 蔚来",
    country: "中国",
    category: "电动车",
    year: 2022,
    priceRMB: "约 45 万元",
    engine: "双电机纯电",
    power: "653 马力",
    topSpeed: 200,
    accel: 3.8,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#00b8d4,#0b2027)",
    emoji: "🔋",
    summary: "能三分钟换一整块电池的智能轿车。",
    description:
      "蔚来 ET7 主打换电模式：开进换电站，机器把车底的电池整块取下、换上满电的，全程约 3 分钟，比充电快得多。车顶那个小凸起是激光雷达，像瞭望塔一样帮车辆看清周围。",
    facts: [
      "换电就像给玩具换电池，只不过这块电池有半吨重。",
      "搭配 150 度电池包时，它的续航超过 1000 公里。",
    ],
  },
  {
    id: "liauto-l9",
    name: "L9",
    brand: "Li Auto 理想",
    country: "中国",
    category: "SUV",
    year: 2022,
    priceRMB: "约 43 万元",
    engine: "1.5T 增程式混动",
    power: "449 马力",
    topSpeed: 180,
    accel: 5.3,
    drivetrain: "四驱",
    seats: 6,
    accent: "linear-gradient(135deg,#2b5876,#4e4376)",
    emoji: "🛋️",
    summary: "自带发电机的六座「移动客厅」。",
    description:
      "理想 L9 用的是增程式技术：发动机不直接驱动车轮，只负责发电，再由电机推动车子。这样既有电车的安静平顺，又不用担心找不到充电桩。车里六个独立座椅加好几块屏幕，像一间会跑的客厅。",
    facts: [
      "增程式相当于随车带了一台「充电宝发动机」。",
      "它的第三排也能坐下成年人，长途出门全家都有座。",
    ],
  },
  {
    id: "xpeng-p7",
    name: "P7",
    brand: "XPeng 小鹏",
    country: "中国",
    category: "电动车",
    year: 2020,
    priceRMB: "约 25 万元",
    engine: "双电机纯电",
    power: "473 马力",
    topSpeed: 200,
    accel: 4.3,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#00c6ff,#0072ff)",
    emoji: "🪽",
    summary: "以智能辅助驾驶著称的溜背轿跑。",
    description:
      "小鹏 P7 有着一路滑到车尾的溜背造型，风阻极低。车身上装满摄像头和雷达，是国内最早把高速与城市辅助驾驶大规模装车的车型之一。",
    facts: [
      "它的风阻系数低到 0.236，比不少超级跑车还小。",
      "贯穿式的「光剑」大灯是小鹏家族的标志。",
    ],
  },
  {
    id: "hongqi-h9",
    name: "H9",
    brand: "Hongqi 红旗",
    country: "中国",
    category: "豪华轿车",
    year: 2020,
    priceRMB: "约 40 万元",
    engine: "3.0T V6 机械增压",
    power: "281 马力",
    topSpeed: 210,
    accel: 6.9,
    drivetrain: "后驱",
    seats: 5,
    accent: "linear-gradient(135deg,#8e0e00,#c0392b)",
    emoji: "🏮",
    summary: "带着国宾车血脉的国产豪华旗舰。",
    description:
      "红旗 H9 车头是标志性的直瀑式格栅，加上引擎盖上高高竖起的立标，气势来自中国第一代国宾车。修长的车身和后排独立座椅，让它成为国产豪华轿车的门面。",
    facts: [
      "红旗品牌诞生于 1958 年，是中国最早的自主轿车品牌之一。",
      "车头立标的造型灵感来自一面迎风飘扬的旗帜。",
    ],
  },
  {
    id: "tank-300",
    name: "坦克 300",
    brand: "GWM 长城",
    country: "中国",
    category: "越野",
    year: 2021,
    priceRMB: "约 22 万元",
    engine: "2.0T 涡轮增压",
    power: "227 马力",
    topSpeed: 170,
    accel: 10.0,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#4b6043,#232b1f)",
    emoji: "🪖",
    summary: "方头方脑的国产硬派越野车。",
    description:
      "坦克 300 用的是非承载式车身——车架和车身分开，像给车装了一副钢铁骨架，越野时更抗扭。配上三把差速锁，泥地、沙漠都能稳稳爬出去。",
    facts: [
      "差速锁能把打滑的轮子「锁住」，让还有抓地力的轮子接着发力。",
      "方正的复古造型让它在车流里一眼就能被认出来。",
    ],
  },
  {
    id: "wuling-mini-ev",
    name: "宏光 MINI EV",
    brand: "Wuling 五菱",
    country: "中国",
    category: "电动车",
    year: 2020,
    priceRMB: "约 4 万元",
    engine: "单电机纯电",
    power: "41 马力",
    topSpeed: 100,
    accel: 15.0,
    drivetrain: "后驱",
    seats: 4,
    accent: "linear-gradient(135deg,#f7b733,#fc4a1a)",
    emoji: "🐣",
    summary: "几万块就能开走的国民小电车。",
    description:
      "宏光 MINI EV 车长不到 3 米，能轻松塞进最窄的车位，价格只要几万元。靠着「城市代步神器」的定位，它曾多次成为中国销量最高的电动车。",
    facts: [
      "两辆它并排停，差不多才占一个普通车位。",
      "它一度是全球单月销量最高的纯电动车。",
    ],
  },
  {
    id: "yangwang-u8",
    name: "仰望 U8",
    brand: "BYD 比亚迪",
    country: "中国",
    category: "SUV",
    year: 2023,
    priceRMB: "约 110 万元",
    engine: "四电机插混（易四方）",
    power: "1180 马力",
    topSpeed: 200,
    accel: 3.6,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#1c1c1c,#8e7f4e)",
    emoji: "🌊",
    summary: "能原地掉头、还能浮在水面的国产 SUV。",
    description:
      "仰望 U8 的四个车轮各有一台独立电机，可以各自正转或反转，因此能像坦克一样原地转圈掉头。车身密封做得极好，紧急情况下还能短时间浮在水面上慢慢开到岸边。",
    facts: [
      "四个独立电机让它能在原地打转，这叫「坦克掉头」。",
      "官方演示里它能在水面漂浮约半小时。",
    ],
  },
  {
    id: "zeekr-001",
    name: "001",
    brand: "Zeekr 极氪",
    country: "中国",
    category: "电动车",
    year: 2021,
    priceRMB: "约 30 万元",
    engine: "双电机纯电",
    power: "789 马力",
    topSpeed: 200,
    accel: 3.3,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#0f766e,#0b1a1a)",
    emoji: "🛰️",
    summary: "猎装造型的高性能纯电旅行车。",
    description:
      "极氪 001 是少见的纯电「猎装车」：车顶从前一路平缓延伸到车尾，既有轿跑的姿态，后备箱又装得下一家人的行李。双电机版本零百加速只要 3.3 秒。",
    facts: [
      "猎装车最早是给猎人装猎枪和猎犬用的旅行车。",
      "它的后备箱容积比很多 SUV 还要大。",
    ],
  },
  {
    id: "hyundai-ioniq5",
    name: "IONIQ 5",
    brand: "Hyundai 现代",
    country: "韩国",
    category: "电动车",
    year: 2021,
    priceRMB: "约 25 万元",
    engine: "双电机纯电",
    power: "325 马力",
    topSpeed: 185,
    accel: 5.2,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#2c3e50,#95a5a6)",
    emoji: "🕹️",
    summary: "用「像素灯」致敬电子游戏的电动车。",
    description:
      "IONIQ 5 的大灯和尾灯由一颗颗方形「像素」组成，像老式电子游戏的画面。它用 800V 高压快充，约 18 分钟就能从 10% 充到 80%，车内插座还能反过来给电器供电。",
    facts: [
      "车灯的方块「像素」造型是在致敬 8 位游戏时代。",
      "露营时可以直接用车上的插座煮火锅、烧水。",
    ],
  },
  {
    id: "kia-ev6",
    name: "EV6 GT",
    brand: "Kia 起亚",
    country: "韩国",
    category: "电动车",
    year: 2021,
    priceRMB: "约 30 万元",
    engine: "双电机纯电",
    power: "585 马力",
    topSpeed: 260,
    accel: 3.5,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#d92027,#2b2b2b)",
    emoji: "⚡",
    summary: "比很多超跑还快的韩系电动车。",
    description:
      "EV6 GT 和 IONIQ 5 出自同一个电动平台，却把性能拉到极致：585 马力、3.5 秒破百，最高车速 260 km/h，还专门做了一个漂移模式按钮。",
    facts: [
      "EV6 拿下过欧洲年度车大奖。",
      "GT 版方向盘上的绿色按钮一按，就切换到最强性能模式。",
    ],
  },
  {
    id: "toyota-supra",
    name: "GR Supra",
    brand: "Toyota 丰田",
    country: "日本",
    category: "跑车",
    year: 2019,
    priceRMB: "约 60 万元",
    engine: "3.0L 直列六缸涡轮增压",
    power: "387 马力",
    topSpeed: 250,
    accel: 4.1,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#c31432,#240b36)",
    emoji: "🐉",
    summary: "直六后驱的日本跑车传奇。",
    description:
      "Supra 是日本跑车文化的图腾，以坚固耐改的直列六缸发动机闻名。第五代 GR Supra 由丰田与宝马联合开发，重新带回长车头、短车尾的经典跑车比例。",
    facts: [
      "上一代那台 2JZ 发动机被改装界称为「能扛住上千马力」。",
      "它因为《速度与激情》系列电影而红遍全世界。",
    ],
  },
  {
    id: "subaru-wrx",
    name: "WRX STI",
    brand: "Subaru 斯巴鲁",
    country: "日本",
    category: "跑车",
    year: 1992,
    priceRMB: "约 35 万元",
    engine: "2.5L 水平对置四缸涡轮增压",
    power: "300 马力",
    topSpeed: 250,
    accel: 5.1,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#0052d4,#0b1e3d)",
    emoji: "🌟",
    summary: "从拉力赛场里长出来的四驱轿车。",
    description:
      "WRX 来自斯巴鲁的世界拉力锦赛经验：水平对置发动机让车子重心很低，配上全时四驱，在雪地和碎石路上格外稳。蓝车身配金色轮毂是它的经典战袍。",
    facts: [
      "水平对置发动机的活塞左右对着运动，像两个拳击手对拳。",
      "车标上的六颗星代表昴星团，日语里「昴」就读作 Subaru。",
    ],
  },
  {
    id: "mitsubishi-evo",
    name: "Lancer Evolution X",
    brand: "Mitsubishi 三菱",
    country: "日本",
    category: "跑车",
    year: 1992,
    priceRMB: "约 30 万元",
    engine: "2.0L 涡轮增压",
    power: "300 马力",
    topSpeed: 250,
    accel: 4.9,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#b31217,#1f1f1f)",
    emoji: "🥊",
    summary: "和 WRX 缠斗二十年的拉力宿敌。",
    description:
      "三菱 Lancer Evolution（车迷简称 EVO）是 WRX 在拉力赛场上的老对手。它的主动偏航控制系统能主动分配左右车轮的动力，让转弯格外犀利，一共进化了十代。",
    facts: [
      "EVO 与 WRX 的对决是汽车史上最著名的宿敌故事之一。",
      "第十代 EVO 于 2016 年停产，成了一代车迷的青春记忆。",
    ],
  },
  {
    id: "suzuki-jimny",
    name: "Jimny 吉姆尼",
    brand: "Suzuki 铃木",
    country: "日本",
    category: "越野",
    year: 1970,
    priceRMB: "约 15 万元",
    engine: "1.5L 自然吸气",
    power: "102 马力",
    topSpeed: 145,
    accel: 12.0,
    drivetrain: "四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#3a6b35,#1c2b1a)",
    emoji: "🐐",
    summary: "个头最小、本事很大的方盒子越野车。",
    description:
      "吉姆尼车长不到 3.7 米，却有硬派越野车的非承载式车身和分时四驱。轻巧的体重让它能钻进大越野车去不了的窄路，被车迷叫做「越野小山羊」。",
    facts: [
      "车轻在越野时是优势：陷进泥里也更容易被拉出来。",
      "从 1970 年到今天，它一直保持着方盒子造型。",
    ],
  },
  {
    id: "toyota-hilux",
    name: "Hilux 海拉克斯",
    brand: "Toyota 丰田",
    country: "日本",
    category: "皮卡",
    year: 1968,
    priceRMB: "约 20 万元",
    engine: "2.8L 柴油涡轮增压",
    power: "204 马力",
    topSpeed: 175,
    accel: 10.7,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#5d4037,#2b1b12)",
    emoji: "🛻",
    summary: "被称为「打不死」的全球皮卡王。",
    description:
      "Hilux 以极端耐用出名，从沙漠到冰原都能见到它。英国的汽车节目曾把它淹在海水里、又放在楼顶炸楼，捞出来修一修居然还能发动。",
    facts: [
      "它曾被开到南极，也开上过冰岛的火山口。",
      "Hilux 在全球 180 多个国家销售，是很多地方唯一靠得住的车。",
    ],
  },
  {
    id: "audi-r8",
    name: "R8 V10",
    brand: "Audi 奥迪",
    country: "德国",
    category: "超级跑车",
    year: 2006,
    priceRMB: "约 200 万元",
    engine: "5.2L V10 自然吸气",
    power: "620 马力",
    topSpeed: 331,
    accel: 3.1,
    drivetrain: "四驱",
    seats: 2,
    accent: "linear-gradient(135deg,#434343,#000000)",
    emoji: "💠",
    summary: "自吸 V10 加四驱的「日常超跑」。",
    description:
      "R8 和兰博基尼 Huracán 共用 V10 发动机与底盘，但调校更温和，加上 quattro 四驱，即使湿滑路面也容易掌控，被称为最好开的超跑之一。",
    facts: [
      "R8 之名来自奥迪的同名勒芒赛车，那台车五次赢下勒芒 24 小时。",
      "它的 V10 是如今越来越稀有的自然吸气高转速发动机。",
    ],
  },
  {
    id: "bmw-m3",
    name: "M3 Competition",
    brand: "BMW 宝马",
    country: "德国",
    category: "跑车",
    year: 1986,
    priceRMB: "约 90 万元",
    engine: "3.0L 直列六缸双涡轮增压",
    power: "510 马力",
    topSpeed: 290,
    accel: 3.5,
    drivetrain: "后驱 / 四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#0052a5,#1c1c1c)",
    emoji: "🔷",
    summary: "能带全家出门的赛道机器。",
    description:
      "M3 由宝马的 M 部门打造，最初是为了参加房车赛而生。它保留四门五座的实用性，却有赛车级的底盘和直六发动机，是「性能与实用兼顾」的代名词。",
    facts: [
      "初代 M3 其实是为了满足赛事规则才量产的赛车衍生版。",
      "M 部门的浅蓝、深蓝、红三色条纹来自宝马赛车历史配色。",
    ],
  },
  {
    id: "mercedes-gclass",
    name: "G-Class G 级",
    brand: "Mercedes-Benz 奔驰",
    country: "德国",
    category: "越野",
    year: 1979,
    priceRMB: "约 180 万元",
    engine: "4.0L V8 双涡轮增压",
    power: "585 马力",
    topSpeed: 240,
    accel: 4.5,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#2c2c2c,#6d6d6d)",
    emoji: "🧱",
    summary: "从军用越野车变成豪车的方盒子。",
    description:
      "G 级最初是为军队开发的越野车，四十多年来外形几乎没变：方灯、外挂备胎、关门时清脆的「咔哒」声。如今车里是顶级豪华配置，底盘却依旧保留三把差速锁的硬派实力。",
    facts: [
      "那声清脆的关门「咔哒」是奔驰刻意保留下来的标志。",
      "它能爬上 100% 的坡（45 度），比大多数楼梯都陡。",
    ],
  },
  {
    id: "vw-t1",
    name: "T1 面包车",
    brand: "Volkswagen 大众",
    country: "德国",
    category: "经典老爷车",
    year: 1950,
    priceRMB: "收藏价 30 万元以上",
    engine: "1.2L 水平对置四缸",
    power: "25 马力",
    topSpeed: 100,
    accel: 40.0,
    drivetrain: "后驱",
    seats: 8,
    accent: "linear-gradient(135deg,#1e88e5,#90caf9)",
    emoji: "🚐",
    summary: "载着一代人旅行梦的圆脸小巴。",
    description:
      "大众 T1 把发动机放在车尾，前面全留给人和行李，于是成了最早的房车与冲浪旅行车。圆润的脸配上 V 形拼色车身，是 1960 年代自由旅行文化的象征。",
    facts: [
      "它的昵称特别多：面包车、Bulli、Kombi、嬉皮巴士。",
      "最早的版本只有 25 马力，上陡坡时乘客得下车帮忙推。",
    ],
  },
  {
    id: "maserati-mc20",
    name: "MC20",
    brand: "Maserati 玛莎拉蒂",
    country: "意大利",
    category: "超级跑车",
    year: 2020,
    priceRMB: "约 300 万元",
    engine: "3.0L V6 双涡轮增压",
    power: "630 马力",
    topSpeed: 325,
    accel: 2.9,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#003366,#7d5a2b)",
    emoji: "🔱",
    summary: "把 F1 点火技术搬上街的三叉戟超跑。",
    description:
      "MC20 的 Nettuno 发动机第一次把 F1 的「预燃室双火花塞」技术用在量产车上，让 3.0 升 V6 榨出 630 马力。碳纤维单体壳车身让整车不到 1.5 吨。",
    facts: [
      "玛莎拉蒂的三叉戟车标来自故乡博洛尼亚的海神喷泉。",
      "Nettuno 在意大利语里就是「海神尼普顿」。",
    ],
  },
  {
    id: "alfa-giulia",
    name: "Giulia 四叶草",
    brand: "Alfa Romeo 阿尔法·罗密欧",
    country: "意大利",
    category: "跑车",
    year: 2015,
    priceRMB: "约 70 万元",
    engine: "2.9L V6 双涡轮增压",
    power: "510 马力",
    topSpeed: 307,
    accel: 3.9,
    drivetrain: "后驱",
    seats: 5,
    accent: "linear-gradient(135deg,#8b0000,#1a1a1a)",
    emoji: "🍀",
    summary: "带着四叶草标的意大利四门快车。",
    description:
      "Giulia 四叶草版的 V6 发动机有法拉利团队参与开发，车身轻巧、转向锐利，曾刷新四门轿车的纽博格林圈速纪录，被车迷称为最有「感情」的性能轿车。",
    facts: [
      "四叶草标志来自 1923 年一位赛车手贴在车上的幸运符。",
      "它的 V6 被认为是法拉利 V8「少两个气缸」的近亲。",
    ],
  },
  {
    id: "fiat-500",
    name: "500 Cinquecento",
    brand: "Fiat 菲亚特",
    country: "意大利",
    category: "经典老爷车",
    year: 1957,
    priceRMB: "收藏价 15 万元以上",
    engine: "0.5L 后置双缸",
    power: "18 马力",
    topSpeed: 95,
    accel: 60.0,
    drivetrain: "后驱",
    seats: 4,
    accent: "linear-gradient(135deg,#f9d423,#e65c00)",
    emoji: "🐞",
    summary: "让意大利人开上车的迷你国民车。",
    description:
      "老 Fiat 500 车长只有 3 米，发动机只有两个气缸，却在战后意大利卖出四百多万辆，把汽车从奢侈品变成了日常工具。它圆润的造型至今被新款 500 沿用。",
    facts: [
      "意大利人昵称它 Cinquecento，意思就是「五百」。",
      "双缸发动机的声音像缝纫机，被戏称为「会跑的洗衣机」。",
    ],
  },
  {
    id: "mclaren-720s",
    name: "720S",
    brand: "McLaren 迈凯伦",
    country: "英国",
    category: "超级跑车",
    year: 2017,
    priceRMB: "约 400 万元",
    engine: "4.0L V8 双涡轮增压",
    power: "720 马力",
    topSpeed: 341,
    accel: 2.9,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#ff8000,#1a1a1a)",
    emoji: "🕶️",
    summary: "把 F1 造车思路带上公路的碳纤维猛兽。",
    description:
      "迈凯伦本身就是 F1 车队。720S 用碳纤维单体壳做骨架，整车只有约 1.4 吨。它「眼窝」式的大灯凹陷既是造型也是散热风道，尾翼在急刹时还会立起来当空气刹车。",
    facts: [
      "720 指的是它的公制马力数。",
      "尾翼立起来时能像降落伞一样帮车子减速。",
    ],
  },
  {
    id: "aston-martin-db11",
    name: "DB11",
    brand: "Aston Martin 阿斯顿·马丁",
    country: "英国",
    category: "跑车",
    year: 2016,
    priceRMB: "约 250 万元",
    engine: "5.2L V12 双涡轮增压",
    power: "639 马力",
    topSpeed: 322,
    accel: 3.7,
    drivetrain: "后驱",
    seats: 4,
    accent: "linear-gradient(135deg,#0b3d2c,#0a0a0a)",
    emoji: "🕴️",
    summary: "007 御用的英式优雅 GT。",
    description:
      "DB11 是阿斯顿·马丁的旗舰 GT：长长的车头、宽阔的车尾，加上羽翼式车标。DB 系列因为詹姆斯·邦德的座驾而闻名世界，是「优雅」与「速度」的结合。",
    facts: [
      "DB 是当年拯救公司的老板 David Brown 的名字缩写。",
      "它把气流从 C 柱内部引出来产生下压力，所以看不到外露的大尾翼。",
    ],
  },
  {
    id: "jaguar-etype",
    name: "E-Type",
    brand: "Jaguar 捷豹",
    country: "英国",
    category: "经典老爷车",
    year: 1961,
    priceRMB: "收藏价 200 万元以上",
    engine: "3.8L 直列六缸",
    power: "265 马力",
    topSpeed: 241,
    accel: 7.0,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#1b5e20,#0d1f10)",
    emoji: "🐆",
    summary: "被称为「史上最美汽车」的长头跑车。",
    description:
      "捷豹 E-Type 在 1961 年日内瓦车展亮相时惊艳世界：修长得像炮弹的车头、圆润的车尾，还有当年很罕见的四轮独立悬挂和盘式刹车。",
    facts: [
      "据说连恩佐·法拉利都称它是「世界上最美的汽车」。",
      "它的车头造型灵感来自捷豹的勒芒赛车 D-Type。",
    ],
  },
  {
    id: "routemaster",
    name: "Routemaster 双层巴士",
    brand: "AEC",
    country: "英国",
    category: "巴士",
    year: 1954,
    priceRMB: "已退役，收藏车",
    engine: "9.6L 直列六缸柴油",
    power: "115 马力",
    topSpeed: 70,
    accel: 60.0,
    drivetrain: "后驱",
    seats: 64,
    accent: "linear-gradient(135deg,#c62828,#7f1010)",
    emoji: "🚌",
    summary: "伦敦街头那张红色的城市名片。",
    description:
      "Routemaster 是伦敦的城市符号：红色车身、车尾敞开的上车口，乘客可以随时跳上跳下，车上还有一位售票员。它服役了半个世纪，如今仍有观光线路在跑。",
    facts: [
      "车尾没有门，等红灯时乘客可以直接跳上车。",
      "它用铝合金做车身，在 1950 年代是很先进的轻量化设计。",
    ],
  },
  {
    id: "ford-f150",
    name: "F-150",
    brand: "Ford 福特",
    country: "美国",
    category: "皮卡",
    year: 1975,
    priceRMB: "约 40 万元",
    engine: "3.5L V6 双涡轮增压",
    power: "400 马力",
    topSpeed: 170,
    accel: 5.9,
    drivetrain: "四驱",
    seats: 6,
    accent: "linear-gradient(135deg,#1565c0,#0b2545)",
    emoji: "🛻",
    summary: "连续四十多年的美国销量冠军。",
    description:
      "F-150 是美国最畅销的车：前排后排能坐五六个人，后面的货箱装得下建材、摩托车甚至家具。新款车上带发电插座，可以直接当移动发电机用。",
    facts: [
      "F 系列连续四十多年是美国销量第一的车型。",
      "车上的发电功率足够带动电锯和整套露营设备。",
    ],
  },
  {
    id: "dodge-challenger",
    name: "Challenger Hellcat",
    brand: "Dodge 道奇",
    country: "美国",
    category: "跑车",
    year: 1970,
    priceRMB: "约 70 万元",
    engine: "6.2L V8 机械增压",
    power: "717 马力",
    topSpeed: 320,
    accel: 3.6,
    drivetrain: "后驱",
    seats: 5,
    accent: "linear-gradient(135deg,#37474f,#0d1418)",
    emoji: "😼",
    summary: "机械增压 V8 的美式肌肉车代表。",
    description:
      "Challenger 是典型的美式肌肉车：又长又宽的车身、巨大的排量。Hellcat 版本靠机械增压把 6.2 升 V8 压出 717 马力，起步时能把后轮烧出滚滚白烟。",
    facts: [
      "Hellcat 意思是「地狱猫」，它配两把钥匙，只有红钥匙才解锁全部马力。",
      "机械增压器由发动机皮带直接带动，一踩油门几乎没有延迟。",
    ],
  },
  {
    id: "chevrolet-camaro",
    name: "Camaro SS",
    brand: "Chevrolet 雪佛兰",
    country: "美国",
    category: "跑车",
    year: 1966,
    priceRMB: "约 45 万元",
    engine: "6.2L V8 自然吸气",
    power: "461 马力",
    topSpeed: 290,
    accel: 4.0,
    drivetrain: "后驱",
    seats: 4,
    accent: "linear-gradient(135deg,#f9a825,#1b1b1b)",
    emoji: "🐝",
    summary: "野马的老对手，也是「大黄蜂」的原型。",
    description:
      "Camaro 是雪佛兰专为对抗福特野马而造的肌肉车，两者的竞争持续了半个多世纪。因为《变形金刚》里的大黄蜂，它成了全世界小朋友最熟悉的美式跑车。",
    facts: [
      "电影《变形金刚》里的大黄蜂，原型就是这台车。",
      "Camaro 与野马的较量被称为「美式肌肉车之战」。",
    ],
  },
  {
    id: "ford-model-t",
    name: "Model T T 型车",
    brand: "Ford 福特",
    country: "美国",
    category: "经典老爷车",
    year: 1908,
    priceRMB: "博物馆藏品",
    engine: "2.9L 直列四缸",
    power: "20 马力",
    topSpeed: 72,
    accel: 60.0,
    drivetrain: "后驱",
    seats: 5,
    accent: "linear-gradient(135deg,#3e2723,#1b1b1b)",
    emoji: "🎩",
    summary: "把汽车带进千家万户的流水线鼻祖。",
    description:
      "福特 T 型车用移动装配流水线，把造一辆车的时间从 12 小时压到 93 分钟，价格一路降到普通工人也买得起，一共卖出 1500 万辆，彻底改变了人类的出行方式。",
    facts: [
      "流水线让装配一辆车的时间缩短到约一个半小时。",
      "亨利·福特说过：「顾客可以要任何颜色，只要它是黑色的。」因为黑漆干得最快。",
    ],
  },
  {
    id: "cat-797",
    name: "797F 矿用卡车",
    brand: "Caterpillar 卡特彼勒",
    country: "美国",
    category: "工程车",
    year: 1998,
    priceRMB: "约 3000 万元",
    engine: "20 缸柴油发动机",
    power: "4000 马力",
    topSpeed: 68,
    accel: 60.0,
    drivetrain: "后驱",
    seats: 1,
    accent: "linear-gradient(135deg,#ffb300,#5d4037)",
    emoji: "🏗️",
    summary: "一车能装近 400 吨石头的钢铁巨兽。",
    description:
      "卡特彼勒 797F 是世界上最大的矿用卡车之一：车高约 6.5 米，一条轮胎就比大人还高，一次能装将近 400 吨矿石。它不上公路，只在矿场里来回搬运。",
    facts: [
      "一条轮胎高约 4 米，比两个成年人叠起来还高。",
      "它的载重量大约相当于同时装上 60 头非洲象。",
    ],
  },
  {
    id: "liebherr-t282",
    name: "T 282B 矿用卡车",
    brand: "Liebherr 利勃海尔",
    country: "德国",
    category: "工程车",
    year: 2004,
    priceRMB: "约 3500 万元",
    engine: "柴油发电 + 轮边电机",
    power: "3650 马力",
    topSpeed: 64,
    accel: 60.0,
    drivetrain: "后驱",
    seats: 1,
    accent: "linear-gradient(135deg,#fdd835,#37474f)",
    emoji: "⛏️",
    summary: "柴油发电、电机驱动的矿场巨无霸。",
    description:
      "T 282B 采用「柴油发电 + 电机驱动」：柴油机只管发电，再由装在车轮里的电机推动车子，因此能轻松搬运 360 吨以上的矿石。它空车就有两百多吨重。",
    facts: [
      "它和火车头用的是同一种「柴电」驱动方式。",
      "司机要爬上几层楼高的梯子才能进驾驶室。",
    ],
  },
  {
    id: "rosenbauer-panther",
    name: "Panther 机场消防车",
    brand: "Rosenbauer 罗森巴尔",
    country: "奥地利",
    category: "卡车",
    year: 1991,
    priceRMB: "约 800 万元",
    engine: "V8 柴油发动机",
    power: "1050 马力",
    topSpeed: 135,
    accel: 25.0,
    drivetrain: "四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#e53935,#7f0000)",
    emoji: "🚒",
    summary: "为机场火灾而生的超级消防车。",
    description:
      "Panther 是专门守在机场的消防车：车上带着十几吨水和泡沫，却能在几十秒内加速到 80 km/h 冲到跑道尽头。车顶的水炮每分钟可以喷出几千升水。",
    facts: [
      "机场消防车必须在 3 分钟内赶到跑道上的任何一点。",
      "车顶水炮的射程能超过 90 米，比一个足球场还长。",
    ],
  },
  {
    id: "volvo-fh",
    name: "FH16 重型卡车",
    brand: "Volvo 沃尔沃",
    country: "瑞典",
    category: "卡车",
    year: 1993,
    priceRMB: "约 100 万元",
    engine: "16L 直列六缸柴油",
    power: "750 马力",
    topSpeed: 90,
    accel: 30.0,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#1e3c72,#2a5298)",
    emoji: "🚛",
    summary: "拖着几十吨货翻山越岭的公路巨人。",
    description:
      "沃尔沃 FH16 是欧洲最强的量产卡车之一，16 升柴油发动机有 750 马力和惊人的扭矩，能牵引几十吨的挂车爬坡。驾驶室里带卧铺，司机可以在车上过夜。",
    facts: [
      "卡车比的不是速度而是扭矩，它的扭矩是超级跑车的好几倍。",
      "沃尔沃卡车拍过让两辆 FH 之间「走钢丝」的著名特技广告。",
    ],
  },
  {
    id: "alpine-a110",
    name: "A110",
    brand: "Alpine 阿尔派",
    country: "法国",
    category: "跑车",
    year: 2017,
    priceRMB: "约 60 万元",
    engine: "1.8L 四缸涡轮增压",
    power: "300 马力",
    topSpeed: 275,
    accel: 4.2,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#0d47a1,#0b2545)",
    emoji: "🏔️",
    summary: "只有 1.1 吨的法国轻量化小跑车。",
    description:
      "阿尔派 A110 复刻了 1960 年代的拉力冠军车：全铝车身让整车只有约 1100 公斤，靠轻巧灵活而不是大马力取胜，被誉为最会转弯的现代跑车之一。",
    facts: [
      "初代 A110 曾赢下蒙特卡洛拉力赛和首届 WRC 车队冠军。",
      "它比同级跑车轻两三百公斤，相当于少载三个人。",
    ],
  },
  {
    id: "porsche-919",
    name: "919 Hybrid",
    brand: "Porsche 保时捷",
    country: "德国",
    category: "赛车",
    year: 2014,
    priceRMB: "非售品",
    engine: "2.0L V4 涡轮增压 + 混动",
    power: "900 马力",
    topSpeed: 350,
    accel: 2.0,
    drivetrain: "四驱",
    seats: 1,
    accent: "linear-gradient(135deg,#9e9e9e,#212121)",
    emoji: "🏁",
    summary: "勒芒三连冠的混动原型赛车。",
    description:
      "919 Hybrid 是保时捷为勒芒 24 小时耐力赛打造的混动原型车，2015 到 2017 年三连冠。它能一边跑一边把刹车和废气的能量回收成电，再释放出来加速。",
    facts: [
      "它的进化版 919 Evo 曾刷新纽博格林北环最快圈速纪录。",
      "勒芒比赛要连续跑 24 小时，一场下来赛车要跑五千多公里。",
    ],
  },
  {
    id: "redbull-rb19",
    name: "RB19",
    brand: "Red Bull Racing 红牛车队",
    country: "英国",
    category: "赛车",
    year: 2023,
    priceRMB: "非售品",
    engine: "1.6L V6 涡轮混动",
    power: "1000 马力",
    topSpeed: 350,
    accel: 2.6,
    drivetrain: "后驱",
    seats: 1,
    accent: "linear-gradient(135deg,#0600ef,#1e1e2f)",
    emoji: "🏆",
    summary: "F1 历史上胜率最高的赛车之一。",
    description:
      "RB19 是 2023 年 F1 赛季的绝对统治者，全年 22 站赢下 21 站。它靠车身产生的巨大下压力把自己「吸」在地面上，所以能以极高的速度过弯。",
    facts: [
      "2023 赛季它在 22 场比赛里赢了 21 场。",
      "高速时产生的下压力超过车身重量，理论上它能贴着隧道顶倒着开。",
    ],
  },
];

// 真实车型照片（来源：Wikimedia Commons，自由授权）
// 已通过代理下载到本地 images/ 目录，运行时完全离线可用，无需外网。
// 如需重新下载或新增，可运行 download_images.ps1。
const CARS_WITH_IMAGE = [
  "bugatti-chiron", "ferrari-f8", "lamborghini-aventador", "porsche-911", "mazda-mx5",
  "nissan-gtr", "toyota-corolla", "vw-golf", "mercedes-sclass", "rolls-royce-phantom",
  "bentley-continental", "tesla-model-s", "byd-han", "porsche-taycan", "landrover-defender",
  "jeep-wrangler", "toyota-landcruiser", "bmw-x5", "range-rover", "ford-mustang",
  "chevrolet-corvette", "koenigsegg-jesko", "volvo-xc90", "citroen-ds", "vw-beetle",
  "mini-cooper", "honda-civic",
  "xiaomi-su7", "nio-et7", "liauto-l9", "xpeng-p7", "hongqi-h9",
  "tank-300", "wuling-mini-ev", "yangwang-u8", "zeekr-001", "hyundai-ioniq5",
  "kia-ev6", "toyota-supra", "subaru-wrx", "mitsubishi-evo", "suzuki-jimny",
  "toyota-hilux", "audi-r8", "bmw-m3", "mercedes-gclass", "vw-t1",
  "maserati-mc20", "alfa-giulia", "fiat-500", "mclaren-720s", "aston-martin-db11",
  "jaguar-etype", "routemaster", "ford-f150", "dodge-challenger", "chevrolet-camaro",
  "ford-model-t", "cat-797", "liebherr-t282", "rosenbauer-panther", "volvo-fh",
  "alpine-a110", "porsche-919", "redbull-rb19",
];

CARS.forEach((c) => {
  c.image = CARS_WITH_IMAGE.includes(c.id) ? `images/${c.id}.webp` : null;
});

// 供 app.js 使用
window.CARS = CARS;
