// 全球汽车科普数据集
// 字段说明：
//   id           唯一标识
//   name         车型名称
//   brand        品牌
//   country      产地/国家
//   category     类型（超级跑车 / 跑车 / 豪华轿车 / SUV / 电动车 / 越野 / 经典老爷车 / 家用轿车）
//   year         代表年份 / 车型年代
//   priceRMB     参考价格区间（人民币，近似）
//   engine       动力形式
//   power        最大功率
//   topSpeed     最高车速（km/h）
//   accel        0-100 km/h 加速（秒）
//   drivetrain   驱动形式
//   seats        座位数
//   accent       主题渐变色（用于卡片配色）
//   emoji        代表图标
//   summary      一句话简介
//   description  科普正文
//   facts        冷知识 / 有趣事实（数组）

const CARS = [
  {
    id: "bugatti-chiron",
    name: "Chiron 凯龙",
    brand: "Bugatti 布加迪",
    country: "法国",
    category: "超级跑车",
    year: 2016,
    priceRMB: "约 3000 万元",
    engine: "8.0L W16 四涡轮增压",
    power: "1500 马力",
    topSpeed: 420,
    accel: 2.4,
    drivetrain: "四驱",
    seats: 2,
    accent: "linear-gradient(135deg,#0f2027,#2c5364)",
    emoji: "🏎️",
    summary: "地表最快量产车之一，W16 四涡轮的工程巅峰。",
    description:
      "布加迪 Chiron 搭载独一无二的 8.0 升 W16 发动机，由四个涡轮增压器供气，输出高达 1500 马力。它是对速度、工艺与极致工程的致敬，散热系统每分钟可处理约 6 万升空气。",
    facts: [
      "W16 发动机相当于把两台 V8 拼在一起。",
      "以最高速行驶时，一箱油仅够跑约 9 分钟。",
      "Chiron 之名来自赛车手 Louis Chiron。",
    ],
  },
  {
    id: "ferrari-f8",
    name: "F8 Tributo",
    brand: "Ferrari 法拉利",
    country: "意大利",
    category: "超级跑车",
    year: 2019,
    priceRMB: "约 300 万元",
    engine: "3.9L V8 双涡轮增压",
    power: "720 马力",
    topSpeed: 340,
    accel: 2.9,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#8e0e00,#1f1c18)",
    emoji: "🐎",
    summary: "法拉利跃马精神的中置引擎代表作。",
    description:
      "F8 Tributo 是法拉利对其屡获殊荣的 V8 发动机的致敬之作。中置后驱布局带来极佳的操控平衡，空气动力学套件在保证下压力的同时兼顾了优雅线条。",
    facts: [
      "其 V8 发动机曾多次获得‘国际年度发动机’大奖。",
      "跃马标志源自一战飞行员的战机徽记。",
    ],
  },
  {
    id: "lamborghini-aventador",
    name: "Aventador",
    brand: "Lamborghini 兰博基尼",
    country: "意大利",
    category: "超级跑车",
    year: 2011,
    priceRMB: "约 400 万元",
    engine: "6.5L V12 自然吸气",
    power: "770 马力",
    topSpeed: 350,
    accel: 2.9,
    drivetrain: "四驱",
    seats: 2,
    accent: "linear-gradient(135deg,#f7971e,#3a1c00)",
    emoji: "🐂",
    summary: "剪刀门与自吸 V12 的狂野图腾。",
    description:
      "Aventador 以标志性的剪刀门和轰鸣的自然吸气 V12 发动机成为超跑图腾。棱角分明的楔形设计灵感来自战斗机与隐形战机。",
    facts: [
      "兰博基尼车型多以著名斗牛命名。",
      "Aventador 是一头曾在斗牛场英勇战斗的公牛之名。",
    ],
  },
  {
    id: "porsche-911",
    name: "911 Carrera",
    brand: "Porsche 保时捷",
    country: "德国",
    category: "跑车",
    year: 1963,
    priceRMB: "约 130 万元起",
    engine: "3.0L 水平对置六缸涡轮增压",
    power: "385 马力",
    topSpeed: 293,
    accel: 4.0,
    drivetrain: "后驱 / 四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#414345,#232526)",
    emoji: "🛞",
    summary: "延续 60 年的后置引擎跑车传奇。",
    description:
      "保时捷 911 是史上最具辨识度的跑车之一，标志性的后置水平对置发动机布局延续超过一甲子。它兼顾了日常实用性与赛道性能，被誉为‘最好开的超跑’。",
    facts: [
      "911 采用罕见的后置后驱布局，重心独特。",
      "初代 911 因商标问题曾短暂命名为 901。",
    ],
  },
  {
    id: "mazda-mx5",
    name: "MX-5 Miata",
    brand: "Mazda 马自达",
    country: "日本",
    category: "跑车",
    year: 1989,
    priceRMB: "约 30 万元",
    engine: "2.0L 直列四缸自然吸气",
    power: "181 马力",
    topSpeed: 219,
    accel: 6.5,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#e53935,#b71c1c)",
    emoji: "🌤️",
    summary: "史上最畅销的双座敞篷跑车。",
    description:
      "MX-5 用轻量化和精准操控证明了‘乐趣与马力无关’。它是吉尼斯世界纪录认证的最畅销双座敞篷跑车，秉承日语‘人马一体’的设计哲学。",
    facts: [
      "累计销量超过 100 万辆。",
      "设计哲学源自英国经典小跑车 Lotus Elan。",
    ],
  },
  {
    id: "nissan-gtr",
    name: "GT-R R35",
    brand: "Nissan 日产",
    country: "日本",
    category: "跑车",
    year: 2007,
    priceRMB: "约 170 万元",
    engine: "3.8L V6 双涡轮增压",
    power: "570 马力",
    topSpeed: 315,
    accel: 2.9,
    drivetrain: "四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#0575e6,#021b79)",
    emoji: "⚔️",
    summary: "绰号‘战神’的性价比性能怪兽。",
    description:
      "日产 GT-R 凭借先进的四驱系统和双涡轮 V6，以远低于欧洲超跑的价格实现媲美的加速表现，被车迷誉为‘平民超跑’与‘东瀛战神’。",
    facts: [
      "每台发动机由专属工匠手工组装并署名。",
      "曾在纽博格林赛道刷新量产车圈速纪录。",
    ],
  },
  {
    id: "toyota-corolla",
    name: "Corolla 卡罗拉",
    brand: "Toyota 丰田",
    country: "日本",
    category: "家用轿车",
    year: 1966,
    priceRMB: "约 12 万元",
    engine: "1.8L 混合动力",
    power: "122 马力",
    topSpeed: 180,
    accel: 10.9,
    drivetrain: "前驱",
    seats: 5,
    accent: "linear-gradient(135deg,#56ab2f,#a8e063)",
    emoji: "🚗",
    summary: "史上销量第一的传奇家用车。",
    description:
      "卡罗拉是全球累计销量最高的车型，以耐用、省油、低故障率著称，是无数家庭的第一辆车，堪称‘可靠’的代名词。",
    facts: [
      "全球累计销量超过 5000 万辆。",
      "名字 Corolla 在拉丁语中意为‘花冠’。",
    ],
  },
  {
    id: "vw-golf",
    name: "Golf 高尔夫",
    brand: "Volkswagen 大众",
    country: "德国",
    category: "家用轿车",
    year: 1974,
    priceRMB: "约 14 万元",
    engine: "1.4L 涡轮增压",
    power: "150 马力",
    topSpeed: 216,
    accel: 8.5,
    drivetrain: "前驱",
    seats: 5,
    accent: "linear-gradient(135deg,#334d50,#cbcaa5)",
    emoji: "⛳",
    summary: "定义了‘两厢车’级别的标杆。",
    description:
      "大众高尔夫开创并定义了紧凑型两厢车市场，其 GTI 版本更缔造了‘钢炮’（Hot Hatch）文化，兼具实用与驾驶乐趣。",
    facts: [
      "Golf 的名字并非高尔夫球，而是德语中的‘湾流’（Gulf Stream）。",
      "GTI 是‘热血小钢炮’的鼻祖之一。",
    ],
  },
  {
    id: "mercedes-sclass",
    name: "S-Class S级",
    brand: "Mercedes-Benz 奔驰",
    country: "德国",
    category: "豪华轿车",
    year: 1972,
    priceRMB: "约 95 万元起",
    engine: "3.0L 直六 + 48V 轻混",
    power: "435 马力",
    topSpeed: 250,
    accel: 4.9,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#232526,#5b6467)",
    emoji: "🎩",
    summary: "汽车科技的‘旗舰试验田’。",
    description:
      "奔驰 S 级长期作为汽车工业的技术风向标，许多如今普及的安全与舒适配置（安全气囊、ABS、ESP）都最早在 S 级上量产应用。",
    facts: [
      "很多主动安全技术都是在 S 级上首发。",
      "三叉星标志代表‘海、陆、空’皆能称霸。",
    ],
  },
  {
    id: "rolls-royce-phantom",
    name: "Phantom 幻影",
    brand: "Rolls-Royce 劳斯莱斯",
    country: "英国",
    category: "豪华轿车",
    year: 1925,
    priceRMB: "约 1000 万元起",
    engine: "6.75L V12 双涡轮增压",
    power: "571 马力",
    topSpeed: 250,
    accel: 5.4,
    drivetrain: "后驱",
    seats: 5,
    accent: "linear-gradient(135deg,#141e30,#243b55)",
    emoji: "👑",
    summary: "顶级手工奢华与静谧的代名词。",
    description:
      "劳斯莱斯幻影是极致奢华的象征，车内静谧到近乎‘无声’。车头的‘欢庆女神’立标与可定制的星空顶棚是其经典标志。",
    facts: [
      "车顶‘星空顶’可由上千根光纤模拟夜空。",
      "‘欢庆女神’立标遇撞击或盗窃会自动缩回车内。",
    ],
  },
  {
    id: "bentley-continental",
    name: "Continental GT",
    brand: "Bentley 宾利",
    country: "英国",
    category: "豪华轿车",
    year: 2003,
    priceRMB: "约 260 万元",
    engine: "6.0L W12 双涡轮增压",
    power: "659 马力",
    topSpeed: 335,
    accel: 3.5,
    drivetrain: "四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#1d4350,#a43931)",
    emoji: "🥂",
    summary: "能优雅巡航也能高速狂奔的豪华GT。",
    description:
      "宾利欧陆 GT 融合了英伦手工内饰与澎湃动力，是‘绅士的高性能座驾’，兼具长途舒适与惊人性能。",
    facts: [
      "内饰真皮与实木均为手工打造，耗时上百小时。",
      "宾利曾在勒芒 24 小时耐力赛多次夺冠。",
    ],
  },
  {
    id: "tesla-model-s",
    name: "Model S Plaid",
    brand: "Tesla 特斯拉",
    country: "美国",
    category: "电动车",
    year: 2012,
    priceRMB: "约 90 万元",
    engine: "三电机纯电动",
    power: "1020 马力",
    topSpeed: 322,
    accel: 2.1,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#c31432,#240b36)",
    emoji: "⚡",
    summary: "重新定义电动车性能的标杆。",
    description:
      "特斯拉 Model S Plaid 用三电机布局实现了媲美超跑的加速，同时保持了轿车的实用性与超长续航，推动了全球电动化浪潮。",
    facts: [
      "Plaid 之名来自科幻喜剧《太空炮弹》中的‘格子超光速’。",
      "0-100 km/h 加速比大多数燃油超跑还快。",
    ],
  },
  {
    id: "byd-han",
    name: "汉 EV",
    brand: "BYD 比亚迪",
    country: "中国",
    category: "电动车",
    year: 2020,
    priceRMB: "约 22 万元",
    engine: "双电机纯电动",
    power: "517 马力",
    topSpeed: 180,
    accel: 3.9,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#0052d4,#4364f7)",
    emoji: "🐉",
    summary: "搭载刀片电池的中国新能源代表。",
    description:
      "比亚迪汉搭载自研‘刀片电池’，在安全性与空间利用率上实现突破，是中国品牌向高端新能源市场进军的标志性车型。",
    facts: [
      "‘刀片电池’通过了严苛的针刺测试，安全性突出。",
      "比亚迪最初是做电池起家的企业。",
    ],
  },
  {
    id: "porsche-taycan",
    name: "Taycan",
    brand: "Porsche 保时捷",
    country: "德国",
    category: "电动车",
    year: 2019,
    priceRMB: "约 100 万元",
    engine: "双电机纯电动",
    power: "761 马力",
    topSpeed: 260,
    accel: 2.8,
    drivetrain: "四驱",
    seats: 4,
    accent: "linear-gradient(135deg,#2b5876,#4e4376)",
    emoji: "🔌",
    summary: "保时捷首款纯电跑车。",
    description:
      "Taycan 是保时捷首款纯电动车，采用领先的 800V 高压架构，兼顾了极致的驾驶质感与快速充电能力。",
    facts: [
      "800V 架构可实现更快充电、更细电缆。",
      "Taycan 在土耳其语中意为‘活泼的小马驹’。",
    ],
  },
  {
    id: "landrover-defender",
    name: "Defender 卫士",
    brand: "Land Rover 路虎",
    country: "英国",
    category: "越野",
    year: 1983,
    priceRMB: "约 80 万元",
    engine: "3.0L 直六 + 轻混",
    power: "400 马力",
    topSpeed: 208,
    accel: 6.1,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#3e5151,#decba4)",
    emoji: "🏔️",
    summary: "征服荒野的英伦硬派越野。",
    description:
      "路虎卫士是硬派越野的传奇，从非洲草原到极地探险都有它的身影。新一代在保留越野硬实力的同时增添了现代豪华科技。",
    facts: [
      "老款卫士曾是英国女王最爱的座驾之一。",
      "极强的涉水与攀爬能力使其成为探险队标配。",
    ],
  },
  {
    id: "jeep-wrangler",
    name: "Wrangler 牧马人",
    brand: "Jeep",
    country: "美国",
    category: "越野",
    year: 1986,
    priceRMB: "约 45 万元",
    engine: "2.0L 涡轮增压",
    power: "272 马力",
    topSpeed: 180,
    accel: 6.7,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#4b6cb7,#182848)",
    emoji: "🧭",
    summary: "源自二战军车的越野图腾。",
    description:
      "Jeep 牧马人血统源自二战军用吉普，标志性的七孔进气格栅、可拆卸车门与车顶是其自由不羁精神的象征。",
    facts: [
      "经典的‘七孔格栅’是 Jeep 的注册标志。",
      "车门和车顶都可拆卸，享受纯粹敞篷越野。",
    ],
  },
  {
    id: "toyota-landcruiser",
    name: "Land Cruiser 陆地巡洋舰",
    brand: "Toyota 丰田",
    country: "日本",
    category: "越野",
    year: 1951,
    priceRMB: "约 90 万元",
    engine: "3.5L V6 双涡轮增压",
    power: "415 马力",
    topSpeed: 210,
    accel: 6.7,
    drivetrain: "四驱",
    seats: 7,
    accent: "linear-gradient(135deg,#603813,#b29f94)",
    emoji: "🗺️",
    summary: "以可靠著称的‘沙漠之王’。",
    description:
      "丰田陆地巡洋舰以极致的耐用性和可靠性闻名，在中东、非洲和澳洲的严酷环境中被广泛信赖，是穿越无人区的首选。",
    facts: [
      "在许多偏远地区，它被视为‘开不坏’的代名词。",
      "联合国与救援组织常选用它作为任务车辆。",
    ],
  },
  {
    id: "bmw-x5",
    name: "X5",
    brand: "BMW 宝马",
    country: "德国",
    category: "SUV",
    year: 1999,
    priceRMB: "约 65 万元",
    engine: "3.0L 直六涡轮增压",
    power: "340 马力",
    topSpeed: 243,
    accel: 5.4,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#005c97,#363795)",
    emoji: "🏙️",
    summary: "开创豪华运动 SUV 的先河。",
    description:
      "宝马 X5 是最早将轿车般操控带入 SUV 的车型之一，被称为‘运动型多用途车（SAV）’，兼顾空间、豪华与驾驶乐趣。",
    facts: [
      "宝马称其为 SAV（运动型多功能车）以强调操控。",
      "蓝白徽标源自巴伐利亚州旗，也常被解读为旋转的螺旋桨。",
    ],
  },
  {
    id: "range-rover",
    name: "Range Rover 揽胜",
    brand: "Land Rover 路虎",
    country: "英国",
    category: "SUV",
    year: 1970,
    priceRMB: "约 150 万元",
    engine: "4.4L V8 双涡轮增压",
    power: "530 马力",
    topSpeed: 250,
    accel: 4.6,
    drivetrain: "四驱",
    seats: 5,
    accent: "linear-gradient(135deg,#232526,#414345)",
    emoji: "🏰",
    summary: "豪华与越野兼备的全能旗舰 SUV。",
    description:
      "揽胜将奢华内饰与强悍越野能力完美结合，是‘公路上的绅士、荒野中的斗士’，深受名流与王室青睐。",
    facts: [
      "揽胜是最早把真正豪华引入越野车的车型。",
      "空气悬挂可大幅升降车身以适应不同路况。",
    ],
  },
  {
    id: "ford-mustang",
    name: "Mustang 野马",
    brand: "Ford 福特",
    country: "美国",
    category: "跑车",
    year: 1964,
    priceRMB: "约 45 万元",
    engine: "5.0L V8 自然吸气",
    power: "466 马力",
    topSpeed: 250,
    accel: 4.3,
    drivetrain: "后驱",
    seats: 4,
    accent: "linear-gradient(135deg,#870000,#190a05)",
    emoji: "🐴",
    summary: "美式肌肉车文化的经典图腾。",
    description:
      "福特野马开创了‘Pony Car’品类，以亲民价格提供大排量 V8 的推背感和肌肉车造型，是美式汽车文化的象征。",
    facts: [
      "上市首年即售出超过 40 万辆，创下纪录。",
      "无数好莱坞电影中的追车戏都少不了它的身影。",
    ],
  },
  {
    id: "chevrolet-corvette",
    name: "Corvette C8",
    brand: "Chevrolet 雪佛兰",
    country: "美国",
    category: "跑车",
    year: 2020,
    priceRMB: "约 80 万元",
    engine: "6.2L V8 自然吸气",
    power: "495 马力",
    topSpeed: 312,
    accel: 2.9,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#f12711,#f5af19)",
    emoji: "🌟",
    summary: "转为中置引擎的美国国民超跑。",
    description:
      "第八代 Corvette 首次采用中置发动机布局，以远低于欧洲超跑的价格提供接近的性能，被誉为‘美国人的法拉利’。",
    facts: [
      "C8 是 Corvette 历史上首款中置引擎版本。",
      "Corvette 之名来自一种轻型快速的护卫舰。",
    ],
  },
  {
    id: "koenigsegg-jesko",
    name: "Jesko",
    brand: "Koenigsegg 柯尼塞格",
    country: "瑞典",
    category: "超级跑车",
    year: 2019,
    priceRMB: "约 2000 万元",
    engine: "5.0L V8 双涡轮增压",
    power: "1600 马力",
    topSpeed: 480,
    accel: 2.5,
    drivetrain: "后驱",
    seats: 2,
    accent: "linear-gradient(135deg,#000428,#004e92)",
    emoji: "🚀",
    summary: "冲击 500 km/h 极速的瑞典超跑。",
    description:
      "柯尼塞格 Jesko 拥有极致的空气动力学与创新变速箱技术，其 Absolut 版本以挑战量产车最高时速为目标，是纯粹的工程艺术品。",
    facts: [
      "Jesko 以创始人父亲的名字命名。",
      "使用烈性乙醇燃料时功率可达 1600 马力。",
    ],
  },
  {
    id: "volvo-xc90",
    name: "XC90",
    brand: "Volvo 沃尔沃",
    country: "瑞典",
    category: "SUV",
    year: 2002,
    priceRMB: "约 55 万元",
    engine: "2.0L 涡轮增压 + 轻混",
    power: "250 马力",
    topSpeed: 220,
    accel: 8.0,
    drivetrain: "四驱",
    seats: 7,
    accent: "linear-gradient(135deg,#136a8a,#267871)",
    emoji: "🛡️",
    summary: "以安全著称的北欧豪华 SUV。",
    description:
      "沃尔沃 XC90 是安全科技的集大成者，城市安全系统、侧气帘等诸多主动安全技术使其成为‘最安全家用车’的代表。",
    facts: [
      "三点式安全带正是沃尔沃发明并无偿公开的。",
      "沃尔沃承诺以零伤亡为长期安全目标。",
    ],
  },
  {
    id: "citroen-ds",
    name: "DS 女神",
    brand: "Citroën 雪铁龙",
    country: "法国",
    category: "经典老爷车",
    year: 1955,
    priceRMB: "收藏级",
    engine: "2.3L 直列四缸",
    power: "115 马力",
    topSpeed: 188,
    accel: 10.4,
    drivetrain: "前驱",
    seats: 5,
    accent: "linear-gradient(135deg,#654ea3,#eaafc8)",
    emoji: "🌈",
    summary: "超越时代的空气悬挂先驱。",
    description:
      "雪铁龙 DS 在 1955 年问世时以流线造型和液压自适应悬挂震惊世界，法语‘DS’发音同‘女神’（Déesse），至今仍是设计史经典。",
    facts: [
      "曾在戴高乐总统遇袭时凭借液压悬挂高速脱险。",
      "液压悬挂让车辆即使爆胎也能平稳行驶。",
    ],
  },
  {
    id: "vw-beetle",
    name: "Beetle 甲壳虫",
    brand: "Volkswagen 大众",
    country: "德国",
    category: "经典老爷车",
    year: 1938,
    priceRMB: "收藏级",
    engine: "1.6L 水平对置四缸",
    power: "50 马力",
    topSpeed: 130,
    accel: 18.0,
    drivetrain: "后驱",
    seats: 4,
    accent: "linear-gradient(135deg,#f8b500,#fceabb)",
    emoji: "🐞",
    summary: "史上最具亲和力的国民小车。",
    description:
      "大众甲壳虫以圆润可爱的造型和后置风冷发动机风靡全球，是 20 世纪产量最大的单一车型之一，承载了几代人的记忆。",
    facts: [
      "累计产量超过 2100 万辆。",
      "圆滚滚的造型让它拥有了‘甲壳虫’这个昵称。",
    ],
  },
  {
    id: "mini-cooper",
    name: "Mini Cooper",
    brand: "Mini",
    country: "英国",
    category: "家用轿车",
    year: 1959,
    priceRMB: "约 25 万元",
    engine: "2.0L 涡轮增压",
    power: "231 马力",
    topSpeed: 246,
    accel: 6.1,
    drivetrain: "前驱",
    seats: 4,
    accent: "linear-gradient(135deg,#e52d27,#b31217)",
    emoji: "🎯",
    summary: "小车身、大乐趣的操控标杆。",
    description:
      "Mini 以极致紧凑的横置前驱布局把空间利用做到极致，其灵活的‘卡丁车’操控和复古时尚造型使它成为都市个性座驾。",
    facts: [
      "横置前驱布局是它节省空间的关键设计。",
      "曾三度夺得蒙特卡洛拉力赛冠军。",
    ],
  },
  {
    id: "honda-civic",
    name: "Civic Type R",
    brand: "Honda 本田",
    country: "日本",
    category: "家用轿车",
    year: 1972,
    priceRMB: "约 30 万元",
    engine: "2.0L 涡轮增压",
    power: "329 马力",
    topSpeed: 275,
    accel: 5.4,
    drivetrain: "前驱",
    seats: 5,
    accent: "linear-gradient(135deg,#cb2d3e,#ef473a)",
    emoji: "🔴",
    summary: "前驱性能车的‘红头’信仰。",
    description:
      "本田思域从家用轿车衍生出的 Type R 高性能版，凭借高转发动机与出色底盘调校，多次刷新前驱车纽北圈速纪录，是‘买发动机送车’的代表。",
    facts: [
      "Type R 的红色本田标是高性能的信仰图腾。",
      "本田是全球产量最大的发动机制造商之一。",
    ],
  },
];

// 真实车型照片（来源：Wikimedia Commons，自由授权）
// 已通过代理下载到本地 images/ 目录，运行时完全离线可用，无需外网。
// 如需重新下载或新增，可运行 download_images.ps1。
const CARS_WITH_IMAGE = [
  "bugatti-chiron", "ferrari-f8", "lamborghini-aventador", "porsche-911", "mazda-mx5",
  "nissan-gtr", "toyota-corolla", "vw-golf", "mercedes-sclass", "rolls-royce-phantom",
  "bentley-continental", "tesla-model-s", "byd-han", "porsche-taycan", "landrover-defender",
  "jeep-wrangler", "toyota-landcruiser", "bmw-x5", "range-rover", "ford-mustang",
  "chevrolet-corvette", "koenigsegg-jesko", "volvo-xc90", "citroen-ds", "vw-beetle",
  "mini-cooper", "honda-civic",
];

CARS.forEach((c) => {
  c.image = CARS_WITH_IMAGE.includes(c.id) ? `images/${c.id}.webp` : null;
});

// 供 app.js 使用
window.CARS = CARS;
